quick-fix construct_network

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,8 +1,71 @@
-name: CI
+name: 'nbdev-ci'
+description: 'Test with nbdev'
 on:  [workflow_dispatch, pull_request, push]
+inputs:
+  pre:
+    description: 'Install prerelease nbdev/execnb from master?'
+    required: false
+    default: ''
+  version:
+    description: 'Version of python to set up'
+    required: false
+    default: '3.9'
+  skip_test:
+    description: 'Skip tests?'
+    required: false
+    default: ''
+  flags:
+    description: 'Space separated list of nbdev test flags to run that are normally ignored'
+    required: false
+    default: ''
 
 jobs:
   test:
     runs-on: ubuntu-latest
-    steps: [uses: fastai/workflows/nbdev-ci@master]
-    
+    steps: 
+        - uses: actions/checkout@v3
+        - uses: actions/setup-python@v4
+          with:
+            python-version: ${{ inputs.version }}
+            cache: "pip"
+            cache-dependency-path: settings.ini
+        - name: Test with nbdev
+          env:
+            USE_PRE: ${{ inputs.pre }}
+            SKIP_TEST: ${{ inputs.skip_test }}
+            FLAGS: ${{ inputs.flags }}
+          shell: bash
+          run: |
+            set -ux
+            python -m pip install --upgrade pip
+            if [ $USE_PRE ]; then
+              pip install -U git+https://github.com/fastai/fastcore.git
+              pip install -U git+https://github.com/fastai/ghapi.git
+              pip install -U git+https://github.com/fastai/execnb.git
+              pip install -U git+https://github.com/fastai/nbdev.git
+            else
+              pip install -U nbdev
+            fi
+            echo "Doing editable install..."
+            test -f setup.py && pip install -e ".[dev]"
+            echo "Check we are starting with clean git checkout"
+            fi
+            echo "Trying to strip out notebooks"
+            nbdev_clean
+            echo "Check that strip out was unnecessary"
+            git status -s # display the status to see which nbs need cleaning up
+            if [[ `git status --porcelain -uno` ]]; then
+              git status -uno
+              echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+              false
+            fi
+            nbdev_export
+            if [[ `git status --porcelain -uno` ]]; then
+              echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+              git status -uno
+              git diff
+              exit 1;
+            fi
+            if [ ! $SKIP_TEST ]; then
+              nbdev_test --flags "$FLAGS"
+            fi
